### ISSUE TITLE
ERROR Error: Runtime compiler is not loaded

### ISSUE THREAD

**Issue by CarstenLeue** [patrikx3/angular-compile#2]
First thank you very much for your awesome work!

I am running into the following issue:
- when compiling my Angular 2 app using @angular/cli with production settings (via `ng build --prod`) I find that the runtime compiler is not available in the resulting package
- the error message is:

> ERROR Error: Runtime compiler is not loaded
> Stack trace:
> y@file:///C:/d/ContentHub/sample-bespoke-pages/data/assets/commerce-details/dist/polyfills.18173234f9641113b9fe.bundle.js:36:2480
> X@file:///C:/d/ContentHub/sample-bespoke-pages/data/assets/commerce-details/dist/vendor.7b61bb9eaee1f6cbbe2c.bundle.js:218:396
> ["3j3K"]/</di</t.prototype.compileModuleAndAllComponentsSync@file:///C:/d/ContentHub/sample-bespoke-pages/data/assets/commerce-details/dist/vendor.7b61bb9eaee1f6cbbe2c.bundle.js:365:302

Adding some debugging output to the constructor of "CompileHtmlService" shows that the injected compiler is empty:

> injected compiler Object {  }

When running the same code in a debug build (via `ng build`) it works fine and shows

>  injected compiler ModuleBoundCompiler {_delegate: JitCompiler, _ngModule: function}

How do I need to provide the runtime compiler so it's available also for the production environment?

**Comment by patrikx3** [comment]
Is it AOT?  I have not fixed it with AOT yet.
Is completely different, because it removed the compiler, it is pre-compiled.

Please check it out:
https://github.com/patrikx3/corifeus-app-web-pages/blob/master/src/angular/module.ts (add in JIT)
https://github.com/patrikx3/corifeus-app-web-pages/blob/master/src/angular/boot.ts (might need COMPILER_PROVIDERS as well)

I started add in the JIT, can you try add in JIT if it works for you? Just my app is a bit complex at the moment... 

But for now it might not work with AOT, I am working it but it's too new, but I will have a new fix sometimes. Also I am using Angular 4 only. Let me know, I think in the end it will want some NgFactory which we dont have since it is dynamic and AOT requires some compiled.

**Comment by patrikx3** [comment]
Until I fix it, you can use (unless the JitCompiler works :) )
```ng build --aot false```

**Comment by CarstenLeue** [comment]
The `--aot false` parameter works as expected, thank you! I'll give the JIT version a try.

**Comment by patrikx3** [comment]
Yeah I created a quick dirty test fix, but even after I had more problems (NgFactory missing, which I will not even have there, will need to look for it more), so I worked on something else, but now I fix it up. I will keep it open and I sent you status. Ciao.

**Comment by CarstenLeue** [comment]
Alright, thanks for your dedication and support!

**Comment by patrikx3** [comment]
I am blocked by Angular.
AOT JitCompiler is broken again in v4 again. 
Not mature enough.
I keep it open, but it will time to make it right.

AOT is faster about about 2 seconds faster.

https://blog.nrwl.io/angular-is-aot-worth-it-8fa02eaf64d4

AOT is larger, plus new build step, while AOT is downloading, JIT can compile at the same time and less time for building (though if it is cached, AOT is faster).

The future is AOT.

**Comment by patrikx3** [comment]
Ciao @CarstenLeue 

I made it. Though it is not out of box.
It works out of the box with compiler:
https://github.com/patrikx3/angular-compile-html/blob/master/test/angular-webpack/angular/module.ts

I added a module. Now you enough to use ```P3XCompileHtmlModule``` out of the box.

Try, if it works with AOT, but I think it will say ```No metadata TemplateModule```.

It is because Google is giving either AOT or JIT and you want both.

I created a builder ```corifeus-builder-angular``` which works, uses webpack.

Also see the note:
https://www.npmjs.com/package/p3x-angular-compile-html
